@echo off
setlocal EnableExtensions EnableDelayedExpansion
cd /d "%~dp0"

rem SimpleParakeet launcher (cmd.exe) - works without PowerShell.
rem Prefer RUN-ME.bat on native Windows; use this under Wine/Proton bottles.

set "ROOT=%CD%"
set "BIN=%ROOT%\bin"
set "LOG=%ROOT%\logs"
set "SETUP_FLAG=%ROOT%\.setup-complete"
set "CONFIG_CMD=%ROOT%\config.cmd"
set "CONFIG_JSON=%ROOT%\config.json"
set "MODEL=%ROOT%\models\tdt_ctc-110m-f16.gguf"

if not exist "%BIN%\parakeet-server.exe" (
  echo Missing bin\parakeet-server.exe
  pause
  exit /b 1
)
if not exist "%BIN%\SimpleParakeet.exe" (
  echo Missing bin\SimpleParakeet.exe
  pause
  exit /b 1
)
if not exist "%MODEL%" (
  echo Missing model: models\tdt_ctc-110m-f16.gguf
  pause
  exit /b 1
)

if not exist "%LOG%" mkdir "%LOG%"

rem Defaults
set "HOST=127.0.0.1"
set "API_PORT=8210"
set "PK_PORT=8211"
set "DEVICE=cpu"

if /I "%~1"=="/setup" if exist "%SETUP_FLAG%" del /q "%SETUP_FLAG%"
if /I "%~1"=="-Setup" if exist "%SETUP_FLAG%" del /q "%SETUP_FLAG%"

if exist "%CONFIG_CMD%" call "%CONFIG_CMD%"

echo.
echo SimpleParakeet
echo.

if not exist "%SETUP_FLAG%" goto :do_setup
goto :start_servers

:do_setup
echo SimpleParakeet setup
echo Press Enter to keep the value in [brackets].
echo.

set /p "IN_HOST=Listen address [%HOST%]: "
if not "%IN_HOST%"=="" set "HOST=%IN_HOST%"

:ask_api
set /p "IN_API=Whisper API port [%API_PORT%]: "
if not "%IN_API%"=="" set "API_PORT=%IN_API%"
call :port_ok %API_PORT%
if errorlevel 1 (
  echo Enter a number between 1 and 65535.
  goto :ask_api
)

:ask_pk
set /p "IN_PK=Internal engine port [%PK_PORT%]: "
if not "%IN_PK%"=="" set "PK_PORT=%IN_PK%"
call :port_ok %PK_PORT%
if errorlevel 1 (
  echo Enter a number between 1 and 65535.
  goto :ask_pk
)
if "%PK_PORT%"=="%API_PORT%" (
  echo Internal engine port must be different from the API port.
  goto :ask_pk
)

rem Persist for cmd + a matching config.json for docs/Windows users
echo rem Generated by launch.cmd - delete .setup-complete to re-run setup> "%CONFIG_CMD%"
echo set "HOST=%HOST%">> "%CONFIG_CMD%"
echo set "API_PORT=%API_PORT%">> "%CONFIG_CMD%"
echo set "PK_PORT=%PK_PORT%">> "%CONFIG_CMD%"
echo set "DEVICE=%DEVICE%">> "%CONFIG_CMD%"

echo {> "%CONFIG_JSON%"
echo   "host": "%HOST%",>> "%CONFIG_JSON%"
echo   "api_port": %API_PORT%,>> "%CONFIG_JSON%"
echo   "parakeet_port": %PK_PORT%,>> "%CONFIG_JSON%"
echo   "device": "%DEVICE%",>> "%CONFIG_JSON%"
echo   "model": "models/tdt_ctc-110m-f16.gguf">> "%CONFIG_JSON%"
echo }>> "%CONFIG_JSON%"

echo. > "%SETUP_FLAG%"
echo.
echo Saved settings.
echo.

:start_servers
set "ENDPOINT=http://%HOST%:%API_PORT%/v1/audio/transcriptions"
set "UPSTREAM=http://%HOST%:%PK_PORT%/v1/audio/transcriptions"

echo Starting backends...
set "PARAKEET_DEVICE=%DEVICE%"
set "PARAKEET_UPSTREAM=%UPSTREAM%"
set "PARAKEET_FFMPEG=%BIN%\ffmpeg.exe"
set "PATH=%BIN%;%PATH%"

rem /B = no extra windows. cmd /c so redirects apply to the child (Wine-friendlier).
start /B "" cmd /c "set PARAKEET_DEVICE=%DEVICE%&& "%BIN%\parakeet-server.exe" --model "%MODEL%" --host %HOST% --port %PK_PORT% > "%LOG%\parakeet.out.log" 2> "%LOG%\parakeet.err.log""
start /B "" cmd /c "set PARAKEET_UPSTREAM=%UPSTREAM%&& set PARAKEET_FFMPEG=%BIN%\ffmpeg.exe&& set PATH=%BIN%;%PATH%&& "%BIN%\SimpleParakeet.exe" --host %HOST% --port %API_PORT% > "%LOG%\api.out.log" 2> "%LOG%\api.err.log""

echo Waiting for API...
set /a TRIES=0
:wait_loop
set /a TRIES+=1
if %TRIES% GTR 90 goto :wait_fail
rem curl.exe ships with modern Windows; often present in Wine bottles too
curl.exe -s -o NUL -f "http://%HOST%:%API_PORT%/health" 2>NUL
if not errorlevel 1 goto :ready
ping -n 2 127.0.0.1 >NUL
goto :wait_loop

:wait_fail
echo API did not become ready. Check logs\api.err.log and logs\parakeet.err.log
call :stop_servers
pause
exit /b 1

:ready
echo.
echo ============================================================
echo  Ready. External Whisper endpoint:
echo.
echo  %ENDPOINT%
echo.
echo  Model: whisper-1
echo  API key: any non-empty value
echo ============================================================
echo.
echo Keep this window open while using speech-to-text.
echo Press Enter to stop.
pause >NUL

call :stop_servers
echo Stopped.
exit /b 0

:stop_servers
rem Broad but simple; fine for a dedicated bottle/prefix
taskkill /F /IM SimpleParakeet.exe >NUL 2>&1
taskkill /F /IM parakeet-server.exe >NUL 2>&1
exit /b 0

:port_ok
set "P=%~1"
echo %P%| findstr /R "^[1-9][0-9]*$" >NUL
if errorlevel 1 exit /b 1
if %P% LSS 1 exit /b 1
if %P% GTR 65535 exit /b 1
exit /b 0
